### ISSUE TITLE
Allow MessageBody to have both HTML and Plaintext coontent

### ISSUE THREAD

**Issue by MetallicCloud** [otterandrye/mailgun_v3#2]
Hello,

This is a useful crate, thanks.  One issue is that (as far as I can tell), you can only send HTML **or** Plaintext emails, but not an email that contains both.  This is important because if HTML isn't supported, it will fallback to plaintext.

I suggest changing `MessageBody` from an Enum to a struct, something like:
```
struct MessageBody
{
    html: Optional<String>,
    text: Optional<String>
};
```

Thoughts?  I'm happy to make a pull request.

Thanks.

**Comment by gnmerritt** [comment]
Am publishing `0.6.0` for you now w/ a `HtmlAndText` message body variant
